---
version: 2.1

executors:
  go-build:
    docker:
      - image: circleci/golang:1.14

commands:
  save-go-mod-cache:
    steps:
      - save_cache:
          key: v1-dependencies-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod

  restore-go-mod-cache:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "go.sum" }}

  save-golangci-lint-cache:
    steps:
      - save_cache:
          key: v1-golangci-lint-{{ checksum "master_sha" }}
          paths:
            - /tmp/golangci-lint-cache

  restore-golangci-lint-cache:
    steps:
      - restore_cache:
          keys:
            - v1-golangci-lint-{{ checksum "master_sha" }}

  save-workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - ./

  restore-workspace:
    steps:
      - attach_workspace:
          at: .

  install-go-protoc:
    steps:
      - run: curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.11.4/protoc-3.11.4-linux-x86_64.zip -o ~/protoc.zip
      - run: unzip ~/protoc.zip -d ~/
      - run: go get google.golang.org/protobuf/cmd/protoc-gen-go

jobs:
  test:
    executor: go-build
    steps:
      - install-go-protoc
      - checkout
      - restore-go-mod-cache
      - run: make master-sha
      - restore-golangci-lint-cache
      # commands
      - run: |
          git config --global user.email circleci
          git config --global user.name circleci
      - run: make
      # persist
      - save-go-mod-cache
      - save-workspace

  release:
    executor: go-build
    steps:
      - setup_remote_docker
      - install-go-protoc
      - restore-workspace
      - restore-go-mod-cache
      - restore-golangci-lint-cache
      # commands
      - run: docker login -u "$QUAY_USER" -p "$QUAY_PASSWD" quay.io
      - run: make push
      - save-golangci-lint-cache

workflows:
  version: 2
  primary:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
